//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitleSoftT.Entity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResKey_dbEntities : DbContext
    {
        public ResKey_dbEntities()
            : base("name=ResKey_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDuInfo> BaiDuInfo { get; set; }
        public virtual DbSet<TitleInfo> TitleInfo { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
